spring:
  application:
    name: backend

  config:
    import: optional:aws-secretsmanager:/secrets/fismadb-secrets;/secrets/fismajwt-secrets


  datasource:
    username: ${username:myuser}
    password: ${password:secret}
    url: jdbc:postgresql://${host:127.0.0.1}:${port:5432}/${dbname:fisma_db}
#    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}


  sql:
    init:
      mode: always


jwt:
  private.key: ${JWT_PRIVATE_KEY:classpath:./local-dev-keys/app.key}
  public.key: ${JWT_PUBLIC_KEY:classpath:./local-dev-keys/app.pub}


logging:
  level:
    org.springframework:
      security: trace


management:
  endpoints:
    web:
      exposure:
        include: health, info



